

/* SE QUISER CRIAR A TABELA ACRESCENTE NO INICIO CREATE TABLE "NOME" AS... */

SELECT F.DEPARTAMENTO AS "Departamento", F.SEXO,
CASE WHEN F.SEXO = 'Masculino' THEN 'M' ELSE 'F'
END AS "Sexo",
	   COUNT(F.CARGO) AS "QUANTIDADE",
	   ROUND(AVG(F.SALARIO),2) AS "MEDIA",
	   MAX(F.SALARIO) AS "MAXIMO",
	   MIN(F.SALARIO) AS "MINIMO",
	   MAX(F.SALARIO) - MIN(F.SALARIO) AS "AMPLIT. TOTAL",
	   ROUND(VAR_POP(F.SALARIO),2) AS "VARIANCIA",
	   ROUND(STDDEV_POP(F.SALARIO),2) AS "DESV. PADRAO",
	   ROUND(MEDIAN(F.SALARIO),2) AS "MEDIANA",
	   ROUND((STDDEV_POP(F.SALARIO) / AVG(F.SALARIO)) * 100,2) AS "COEF. VARIACAO",
	   MODE() WITHIN GROUP(ORDER BY F.CARGO) AS "MODA"
	   FROM FUNCIONARIOS F
	   GROUP BY F.DEPARTAMENTO, F.SEXO
	   ORDER BY 1;